name: test-deploy

on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install php 8.1
          uses: shivammathur/setup-php@v2
            with:
              php-version: 8.1

      - name: Install composer dependencies
          run: composer install --ignore-platform-reqs

      - name: Generate env
        run: cp .env.example .env

      - name: Generate Laravel application key
        run: php artisan key:generate