name: test-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install Composer dependencies
        run: composer install --ignore-platform-reqs

      - name: Generate .env file
        run: cp .env.example .env

      - name: Generate Laravel application key
        run: php artisan key:generate
